import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "./utils/Provider";
import NavBar from "./components/NavBar";
import NavSwitch from "./components/NavSwitch";
import NavComponent from "./components/NavComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Flairweb App",
  description: "Generated by Inpath technologies",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} h-full bg-slate-100 text-black dark:bg-slate-950 dark:text-amber-50 dark:selection:bg-purple-900 selection:bg-purple-100`}
      >
        <Provider>
          <NavComponent />
          <main>{children}</main>
        </Provider>
      </body>
    </html>
  );
}
